### ISSUE TITLE
Iaq on arduino

### ISSUE THREAD

**Issue by martinschki** [DFRobot/DFRobot_BME680#10]
Will iaq be a available for the other arduinos?

**Comment by WeMakeIt1995** [comment]
I'm so sorry to reply you now.......
if there has a new iaq demo support other arduinos, we will message you.
thanks for your feedback.

**Comment by kyriazis** [comment]
I second the request. It's been 11 months since the last update in the IAQ files.  Are there plans for supporting other Arduinos?
