### ISSUE TITLE
Normalised Atmospheric Pressure

### ISSUE THREAD

**Issue by kylix34** [DFRobot/DFRobot_BME680#2]
Hi,

could you add an "ALTITUDE" variable in order to obtain the "Normalised Atmospheric Pressure"?

I have changed the DFRobot_BME680.cpp file, changing the line 206 from:
return P;

into

return (P / pow(1.0 - (43.0 / 44330.0), 5.255));  where "43.0" is the altitude in meters of my location.

It would be nice to have a variable in the sketch so that one could calculate the pressure according to the altitude of the city.

Thanks

**Comment by WeMakeIt1995** [comment]
Thanks for your suggest, we had add a function readSeaLevel to get a "Normalised Atmospheric Pressure"

**Comment by kylix34** [comment]
Thanks!!!!!!!!
