### ISSUE TITLE
invalid conversion from uint8_t 

### ISSUE THREAD

**Issue by pedda4711** [DFRobot/DFRobot_BME680#3]
Hello,
i download the Version from 11.10.2017 today (12.10.2017)
I compile the example  for ess8266 (12e) i get the following error:
--------------------------------
DFRobot_BME680.cpp:66:64: error: invalid conversion from 'uint8_t {aka unsigned char}' to 'uint8_t* {aka unsigned char*}' [-fpermissive]

   bme680_sensor.write(bme680_sensor.dev_id, 0x74, convertCmd, 1);

--------------------------------

**Comment by WeMakeIt1995** [comment]
Thanks for your feedback.
I had resolved it.

**Comment by pedda4711** [comment]
Now it compiles nicely
