### ISSUE TITLE
parameters for the sensor

### ISSUE THREAD

**Issue by martinschki** [DFRobot/DFRobot_BME680#9]
Hi,
where can I adjust those parameters in the code?
would it be possible to have those parameters also available for this sensor?

// Set up oversampling and filter initialization
setTemperatureOversampling(BME680_OS_8X);
setHumidityOversampling(BME680_OS_2X);
setPressureOversampling(BME680_OS_4X);
setIIRFilterSize(BME680_FILTER_SIZE_3);
setGasHeater(320, 150); // 320*C for 150 ms

**Comment by WeMakeIt1995** [comment]
There has a update.
Use function setParam and setGasHeater to modify parament.
You can reference our readme for more info.

**Comment by martinschki** [comment]
Thanks!
